better empty version handling

diff --git a/resmgr/upgrade-resmgr.sh.in b/resmgr/upgrade-resmgr.sh.in
--- a/resmgr/upgrade-resmgr.sh.in
+++ b/resmgr/upgrade-resmgr.sh.in
@@ -11,6 +11,26 @@ serviced snapshot untag $SERVICE_TENANT_ID preupgrade-resmgr-%VERSION%
 
 FROM_VERSION=$(serviced service list resmgr --format='{{.Version}}')
 FROM_VERSION_SHORT=$(cut -d'.' -f1,2 <<< $FROM_VERSION)
+
+if [ -z "$FROM_VERSION" ];
+then
+    FROM_VERSION=$(serviced service list resmgr --format '{{.ImageID}}' | awk '{ print "localhost:5000/"$0" cat /opt/zenoss/Products/ZenModel/ZVersion.py" }' | xargs docker run --rm | grep VERSION | cut -d'"' -f2)
+fi
+
+if [ -z "$FROM_VERSION" ];
+then
+    FROM_VERSION=$(grep 'SVC_USE zenoss/resmgr_[^:_]*:.*' /root/%SHORT_VERSION%.x/current_version.txt | cut -d':' -f2 | cut -d'_' -f1)
+    if [ -z "$FROM_VERSION" ];
+    then
+        echo "Could not get the previous RM version number from serviced, please edit current_version.txt to set it."
+        echo "Change this line 'SVC_USE zenoss/resmgr_REPLACE_1' to reflect the pre-upgrade version, for example:"
+        echo "SVC_USE zenoss/resmgr_5.2:5.2.6_1"
+        exit 1
+    else
+        echo "Using FROM_VERSION provided by change to current_version.txt"
+    fi
+fi
+
 sed -i 's/REPLACE/'"$FROM_VERSION_SHORT:$FROM_VERSION"'/g' /root/%SHORT_VERSION%.x/current_version.txt
 serviced script run /root/%SHORT_VERSION%.x/current_version.txt --service Zenoss.resmgr
 
diff --git a/ucspm/upgrade-ucspm.sh.in b/ucspm/upgrade-ucspm.sh.in
--- a/ucspm/upgrade-ucspm.sh.in
+++ b/ucspm/upgrade-ucspm.sh.in
@@ -11,6 +11,26 @@ serviced snapshot untag $UCSPM_TENANT_ID preupgrade-ucspm-%VERSION%
 
 FROM_VERSION=$(serviced service list ucspm --format='{{.Version}}')
 FROM_VERSION_SHORT=$(cut -d'.' -f1,2 <<< $FROM_VERSION)
+
+if [ -z "$FROM_VERSION" ];
+then
+    FROM_VERSION=$(serviced service list ucspm --format '{{.ImageID}}' | awk '{ print "localhost:5000/"$0" cat /opt/zenoss/Products/ZenModel/ZVersion.py" }' | xargs docker run --rm | grep VERSION | cut -d'"' -f2)
+fi
+
+if [ -z "$FROM_VERSION" ];
+then
+    FROM_VERSION=$(grep 'SVC_USE zenoss/ucspm_[^:_]*:.*' /root/%SHORT_VERSION%.x/current_version.txt | cut -d':' -f2 | cut -d'_' -f1)
+    if [ -z "$FROM_VERSION" ];
+    then
+        echo "Could not get the previous UCSPM version number from serviced, please edit current_version.txt to set it."
+        echo "Change this line 'SVC_USE zenoss/ucspm_REPLACE_1' to reflect the pre-upgrade version, for example:"
+        echo "SVC_USE zenoss/ucspm_2.0:2.0.0_1"
+        exit 1
+    else
+        echo "Using FROM_VERSION provided by change to current_version.txt"
+    fi
+fi
+
 sed -i 's/REPLACE/'"$FROM_VERSION_SHORT:$FROM_VERSION"'/g' /root/%SHORT_VERSION%.x/current_version.txt
 serviced script run /root/%SHORT_VERSION%.x/current_version.txt --service ucspm
 
